name: The Modern Day Hitchhiker
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45622
title: The Modern-day Hitchhiker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a78ec8'
    - '#7173c0'
    - '#4d52ba'
    - '#b67557'
  brandStrength: 0.5
  lightness: 0.9497746429406106
  saturation: 0.5
  rhythmicContrast: 0.1620821573305875
purpose: []
